title: Build end-to-end CI/CD capabilities directly in GitHub
description: With GitHub Actions, you can create and set up workflows in your repository to build, test, and deploy your code.
steps:
  - link: https://github.com/MSUSDEV/end-to-end-github-actions
    title: GitHub ➡️ Presentation Repository
    description: >-
      Review demos and presentation content here
  - link: https://www.youtube.com/watch?v=s-WkdSXRDA4
    video: https://www.youtube.com/embed/s-WkdSXRDA4
    title: Webinar ➡️ Introduction to GitHub Actions
    description: >-
      Learn how GitHub Actions enable you to automate your software development
      cycle and deploy applications to Azure. We’ll walk you through how to
      create a basic GitHub workflow.
  - course: 'githubtraining/github-actions:-hello-world'
  - link: https://docs.microsoft.com/en-us/learn/modules/github-actions-automate-tasks/
    title: Microsoft Learn ➡️ Automate development tasks by using GitHub Actions
    description: >-
      On Microsoft Learn, create a basic GitHub Action and use that action in a workflow.