title: Build end-to-end CI/CD capabilities directly in GitHub
description: >-
  With GitHub Actions, you can create and set up workflows in your repository to
  build, test, and deploy your code to Azure. This webinar training series is
  for teams looking to build end-to-end continuous integration (CI) and
  continuous deployment (CD) capabilities directly in their GitHub
  repositories.     We’ll show you how to create custom CI workflows using
  GitHub Actions that automate building and testing your code so that you can
  get immediate feedback on code changes to detect and resolve bugs faster,
  saving you time.    To automate the deployment process and help to deploy
  tested, stable code changes to customers more quickly, we’ll also show you how
  to use GitHub Actions to create custom CD workflows.  In each session, we’ll
  point you to labs where you can try out our examples for yourself for hands-on
  experience.
steps:
  - link: 'https://www.youtube.com/watch?v=s-WkdSXRDA4'
    video: 'https://www.youtube.com/embed/s-WkdSXRDA4'
    title: Webinar Introduction to GitHub Actions
    description: >-
      Learn how GitHub Actions enable you to automate your software development
      cycle and deploy applications to Azure. We’ll walk you through how to
      create a basic GitHub Action and use that action in a workflow.
