title: CI/CD with GitHub and Azure
description: >-
  With GitHub Actions you can create and set up workflows in your repository to
  build, test, and deploy code to Azure. This path is for those looking to build
  end-to-end continuous integration (CI) and continuous deployment (CD) in their
  repositories.
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
